"""
Created on: 06-30-21
Created by: Devon J. Boland

The purpose of this script is to take a blast out file formatted by argument -outfmt6 and return individual
tsv files for each of the original queries in the  multi-fasta file used as a query in the original blast alginment.

The hits file (a list containing names of the query sequences, can be generated by running the following code with bash:
awk '{print $1}' outfmt6.out | sort | uniq > Hits.txt
"""

import pandas as pd
import argparse as ap

parser = ap.ArgumentParser(description="Program to fragment a blast output (outfmt6) file into query"
                                       "smaller outfmt6 files grouped by query.")
parser.add_argument('input', type=str, help="Blast output file in outfmt6 (ex:blastn.out)")
parser.add_argument("hits", type=str, help="Text file containing list of query sequences (ex:query.txt)")
parser.add_argument("output", type=str, help="Output directory for files (directory must exist) (ex:path/to/output)")
args = parser.parse_args()

with open(args.hits, 'r') as query:
    fulltext = query.read()
    hits = fulltext.split('\n')
    with open(args.input, 'r') as data:
        df = pd.read_csv(data, delimiter='\t', header=None)
        for name in hits:
            with open(args.output+"/"+name+".output", "w+") as output:
                data = df[df[0].str.contains(name)]
                data.to_csv(output, sep='\t', header=None, index=False)